# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulate Birth-Death Cladogenesis Process on Tree
#' 
#' @examples
#' \dontrun{
#' simulate_bd_poisson(seed = 0L,lambda = 1.5,mu = 0.95,duration = 5,maxN = 1e3L,out = "/Users/slwu89/Desktop/out.nwk")
#' MyTree <- ape::read.tree("/Users/slwu89/Desktop/out.nwk")
#' plot(MyTree)
#' }
#' @export
simulate_bd_poisson <- function(seed, lambda, mu, duration, maxN, out) {
    invisible(.Call('_hawkesBD_simulate_bd_poisson', PACKAGE = 'hawkesBD', seed, lambda, mu, duration, maxN, out))
}

