# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulate Birth-Death Cladogenesis Process on Tree
#' 
#' @export
simulate_bd_poisson <- function(seed, lambda, mu, duration, maxN) {
    invisible(.Call('_hawkesBD_simulate_bd_poisson', PACKAGE = 'hawkesBD', seed, lambda, mu, duration, maxN))
}

