// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// simulate_bd_poisson
void simulate_bd_poisson(const unsigned int seed, const double lambda, const double mu, const double duration, const unsigned int maxN);
RcppExport SEXP _hawkesBD_simulate_bd_poisson(SEXP seedSEXP, SEXP lambdaSEXP, SEXP muSEXP, SEXP durationSEXP, SEXP maxNSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const unsigned int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type duration(durationSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type maxN(maxNSEXP);
    simulate_bd_poisson(seed, lambda, mu, duration, maxN);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hawkesBD_simulate_bd_poisson", (DL_FUNC) &_hawkesBD_simulate_bd_poisson, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_hawkesBD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
